# Publishes package to registry (GitHub) on git version tag push

# Pipeline:
# 1. Triggered by tag push
# 2. Set up publish to registry
# 3. Publishes to registry

# Requirements:
# - secrets.ORG_SCOPE

name: Publish npm package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write # Required for OIDC trusted publishing authentication
  contents: read # Required to clone repository
  packages: write # Required to publish npm package to GitHub package registry

jobs:
  publish-github-package:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required to fetch all tags for git operations

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: '24.5.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: ${{ secrets.ORG_SCOPE }}

      - name: Publish to GitHub Packages
        run: npm publish
